[project]
name = "lidar-features"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gtsam>=4.2",
    "rosbags>=0.10.7",
 "tabulate>=0.9.0",
 "tqdm>=4.67.1",
]

[build-system]
requires = ["scikit-build-core", "pybind11", "pybind11-stubgen", "numpy"]
build-backend = "scikit_build_core.build"
